### ISSUE TITLE
Disabled variant reads the wrong lint-results.xml

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.gradle#100]
See `LintOptions_createOutputPath`

```
> Task :android:data:svg:lint
Wrote HTML report to file:///I:/project/android/data/svg/build/reports/lint-results-debug.html
Wrote XML report to file:///I:/project/android/data/svg/build/reports/lint-results-debug.xml
Lint found 1 warning

> Task :lint
Error when parsing I:\project\android\data\svg\build\reports\lint-results.xml as ANDROIDLINT
java.io.FileNotFoundException: I:\project\android\data\svg\build\reports\lint-results.xml (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at se.bjurr.violations.lib.reports.Parser.findViolations(Parser.java:101)
        at net.twisterrob.gradle.quality.gather.LintReportGatherer.findViolations(LintReportGatherer.kt:38)
        at net.twisterrob.gradle.quality.tasks.GlobalLintGlobalFinalizerTask.failOnFailures(GlobalLintGlobalFinalizerTask.kt:37)
```

I think this triggers the problem:
```
android {
	variantFilter { variant ->
		if (variant.buildType.name == com.android.builder.core.BuilderConstants.RELEASE) {
			variant.setIgnore(true)
		}
	}
}
```

**Comment by TWiStErRob** [comment]
Branch fix100
