### ISSUE TITLE
Change in project state between lint and HTML report may misplace files

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.gradle#31]
Lines and files may be moving around, so make generation more lenient and display proper errors for missing stuff.
For example: `lint` was run with `ic_launcher_app` and then it was renamed to `ic_launcher` and then HTML report crashed while reading the outdated lint report.

```
Caused by: java.io.FileNotFoundException: P:\projects\workspace\ColorFilters\app\src\main\res\drawable-hdpi\ic_launcher_app.png (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
        at net.twisterrob.gradle.quality.report.html.ViolationsGrouperKt$emitViolation$1$3$8.invoke(ViolationsGrouper.kt:128)
```

Consider also: detect outdated lint reports? (e.g. `lint-resuts` HTML file is newer than XML)

**Comment by TWiStErRob** [comment]
partially fixed at https://github.com/TWiStErRob/net.twisterrob.gradle/commit/b8375bb8e5141ba44b8f1d64502688ff632962a4#diff-4722b864662b4e530ab1aa7ff44522e3R196
